name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - run: npm run type-check --if-present
      - run: npm run lint
      - run: npm run build
      - run: npm test --if-present
      - name: Audit required files from checklist
        run: |
          grep -q "Master Checklist" docs/CHECKLIST.md
          test -f README.md
          test -f cms.manifest.json
          test -f app/api/admin/health/route.ts
          test -f app/api/pages/route.ts
          test -f app/api/pages/[id]/route.ts
          test -f app/components/DynamicNavigation.tsx
          test -f app/admin/page.tsx
          test -f app/api/upload/route.ts
          # Required public/branding files (best-effort presence checks)
          test -f app/page.tsx
          test -f app/services/page.tsx || true
          test -f app/testimonials/page.tsx || true
          test -f app/gallery/page.tsx || true
          test -f app/about/page.tsx || true
          test -f app/api/contact/route.ts || true
          test -f public/qr.png || true
          test -f branding/logo_black.svg || true
          test -f branding/logo_white.svg || true
          test -f branding/logo_transparent.svg || true
          test -f public/sitemap.xml || true
          test -f public/robots.txt || true

      - name: Audit checklist presence
        run: |
          test -f cms.manifest.json
          test -f docs/CHECKLIST.md

      - name: Audit required paths (allow alternatives)
        run: |
          ok=1
          check() { for p in "$@"; do [ -e "$p" ] && return 0; done; return 1; }
          check app/page.tsx pages/index.tsx || ok=0
          check app/contact/page.tsx pages/contact.tsx || ok=0
          check app/services/page.tsx pages/services.tsx || ok=0
          check app/testimonials/page.tsx pages/testimonials.tsx || ok=0
          check app/gallery/page.tsx pages/gallery.tsx || ok=0
          check app/about/page.tsx pages/about.tsx || ok=0
          check app/admin/page.tsx pages/admin/index.tsx || ok=0
          check app/api/contact/route.ts pages/api/contact.ts || ok=0
          check public/qr.png || ok=0
          check branding/logo_black.svg || ok=0
          check branding/logo_white.svg || ok=0
          check branding/logo_transparent.svg || ok=0
          check public/sitemap.xml || ok=0
          check public/robots.txt || ok=0
          if [ $ok -ne 1 ]; then echo "❌ Checklist audit failed. See docs/CHECKLIST.md"; exit 1; fi
          echo "✅ Checklist audit passed."
