name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-test-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: |
          if [ -f pnpm-lock.yaml ]; then
            corepack enable
            corepack prepare pnpm@latest --activate
            pnpm install --frozen-lockfile
          elif [ -f yarn.lock ]; then
            yarn install --frozen-lockfile
          else
            npm ci
          fi

      - name: Lint
        run: |
          npm run lint --if-present || true
          pnpm lint --if-present || true
          yarn lint --if-present || true

      - name: Typecheck
        run: |
          npm run typecheck --if-present || true
          pnpm typecheck --if-present || true
          yarn typecheck --if-present || true

      - name: Build
        run: |
          npm run build --if-present || true
          pnpm build --if-present || true
          yarn build --if-present || true

      - name: Unit tests
        run: |
          npm test --if-present || true
          pnpm test --if-present || true
          yarn test --if-present || true

      # -------- AUDIT BLOCK (required deliverables) --------
      - name: Audit checklist presence
        run: |
          test -f cms.manifest.json || (echo "Missing cms.manifest.json"; exit 1)
          test -f docs/CHECKLIST.md || (echo "Missing docs/CHECKLIST.md"; exit 1)

      - name: Audit required paths (allow alternatives)
        run: |
          ok=1
          check() { for p in "$@"; do [ -e "$p" ] && return 0; done; return 1; }
          # Core pages (App Router or Pages Router allowed)
          check app/page.tsx pages/index.tsx || { echo "Missing landing page"; ok=0; }
          check app/contact/page.tsx pages/contact.tsx || { echo "Missing contact page"; ok=0; }
          check app/services/page.tsx pages/services.tsx || { echo "Missing services page"; ok=0; }
          check app/testimonials/page.tsx pages/testimonials.tsx || { echo "Missing testimonials page"; ok=0; }
          check app/gallery/page.tsx pages/gallery.tsx || { echo "Missing gallery page"; ok=0; }
          check app/about/page.tsx pages/about.tsx || { echo "Missing about page"; ok=0; }
          # Admin dashboard
          check app/admin/page.tsx pages/admin/index.tsx app/admin/pages/page.tsx || { echo "Missing admin dashboard route"; ok=0; }
          # Contact API
          check app/api/contact/route.ts pages/api/contact.ts || { echo "Missing contact API route"; ok=0; }
          # Assets & branding
          check public/qr.png || { echo "Missing QR code at public/qr.png"; ok=0; }
          check branding/logo_black.svg || { echo "Missing branding/logo_black.svg"; ok=0; }
          check branding/logo_white.svg || { echo "Missing branding/logo_white.svg"; ok=0; }
          check branding/logo_transparent.svg || { echo "Missing branding/logo_transparent.svg"; ok=0; }
          # SEO
          check public/sitemap.xml || { echo "Missing public/sitemap.xml"; ok=0; }
          check public/robots.txt || { echo "Missing public/robots.txt"; ok=0; }
          # CMS visibility
          check app/api/admin/health/route.ts || { echo "Missing admin health endpoint"; ok=0; }
          # Final decision
          if [ $ok -ne 1 ]; then
            echo "❌ Checklist audit failed. See docs/CHECKLIST.md"
            exit 1
          fi
          echo "✅ Checklist audit passed."

      # -------- OPTIONAL: Playwright E2E (run if config exists) --------
      - name: Playwright install (optional)
        if: ${{ hashFiles('playwright.config.*') != '' }}
        run: |
          npx playwright install --with-deps

      - name: E2E tests (optional)
        if: ${{ hashFiles('playwright.config.*') != '' }}
        run: |
          npx playwright test || (echo "Playwright tests failed"; exit 1)

      # Example: upload Playwright report if failed
      - name: Upload Playwright report
        if: failure() && hashFiles('playwright-report/**') != ''
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
